# Generated by Django 3.2.15 on 2022-09-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome da Loja')),
                ('pedido_minimo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pedido Mínimo')),
            ],
        ),
    ]
