# Generated by Django 3.2.15 on 2022-11-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.FileField(default=None, null=True, upload_to='images'),
        ),
    ]
